from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(
    ['momentsModel/momentsModel',
     'shapePrior',
     'starGalaxyPrior',
     'classificationPrior',
     'defaultStarClassificationPrior',
     'galaxyPrior',
    ],
    addUnderscore=False
)
